version: '3.8'

networks:
  justicevault_fabric:
    name: justicevault_fabric

services:
  orderer.justicevault.gov.in:
    image: hyperledger/fabric-orderer:2.5.4
    container_name: orderer.justicevault.gov.in
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=7050
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=false
    ports:
      - "7050:7050"
    networks:
      - justicevault_fabric

  peer0.police.justicevault.gov.in:
    image: hyperledger/fabric-peer:2.5.4
    container_name: peer0.police.justicevault.gov.in
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_ID=peer0.police.justicevault.gov.in
      - CORE_PEER_ADDRESS=peer0.police.justicevault.gov.in:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.police.justicevault.gov.in:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_LOCALMSPID=PoliceHQ.Org1MSP
      - CORE_PEER_TLS_ENABLED=false
    ports:
      - "7051:7051"
    networks:
      - justicevault_fabric

  peer0.forensic.justicevault.gov.in:
    image: hyperledger/fabric-peer:2.5.4
    container_name: peer0.forensic.justicevault.gov.in
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peer0.forensic.justicevault.gov.in
      - CORE_PEER_ADDRESS=peer0.forensic.justicevault.gov.in:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_LOCALMSPID=ForensicLab.Org2MSP
      - CORE_PEER_TLS_ENABLED=false
    ports:
      - "8051:8051"
    networks:
      - justicevault_fabric

  peer0.judiciary.justicevault.gov.in:
    image: hyperledger/fabric-peer:2.5.4
    container_name: peer0.judiciary.justicevault.gov.in
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=peer0.judiciary.justicevault.gov.in
      - CORE_PEER_ADDRESS=peer0.judiciary.justicevault.gov.in:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_LOCALMSPID=Judiciary.Org3MSP
      - CORE_PEER_TLS_ENABLED=false
    ports:
      - "9051:9051"
    networks:
      - justicevault_fabric
